### ISSUE TITLE
User configuration files in GitHub directory

### ISSUE THREAD

**Issue by olivecha** [thiago-glissoi/FFF-Line-Segmentation#1]
This is not critical to the acceptance of the paper, but there are some user specific configuration/system files that have been pushed to the github directory (`.vscode` and `.DS_Store`). They should be removed and added to the `.gitignore`.

**Comment by thiago-glissoi** [comment]
The configuration/system files have been deleted through commits 91ac869 and 07cb20c.
The `.gitignore` was altered through the commit 74af8b2.
