### ISSUE TITLE
Code comments and documentation 

### ISSUE THREAD

**Issue by olivecha** [thiago-glissoi/FFF-Line-Segmentation#2]
While the existing documentation does a decent job at explaining what the code does, it is still hard to understand the code itself when reading the `fff_segmenter.m` file, and I don't think you could expect someone to be able to contribute to it without additional explanations from the author.

At the minimum, function documentation strings should be added and explain every argument, what is returned and what the function does, as described [here](https://www.mathworks.com/help/matlab/matlab_prog/add-help-for-your-program.html).

Also, the code would benefit from additional comments as it is a standalone script without formal API documentation.

**Comment by thiago-glissoi** [comment]
Working on it. Thanks for the review.

**Comment by thiago-glissoi** [comment]
Hey @olivecha

Thanks for the issue!

To address your request, we've added the required function documentation strings and detailed explanations for every argument, return values, and the function's purpose. We've also updated the [Documentation](https://github.com/thiago-glissoi/FFF-Line-Segmentation/blob/main/Documentation.pdf) to increase content, and also improve understanding for the community.

If any further changes are needed, feel free to let us know.

Best,
Thiago

**Comment by olivecha** [comment]
Could you mention the issue number (#2) in the commit messages of the changes addressing the issue ?
(Same for all issues, so we can track what was done to remediate the issues)

**Comment by thiago-glissoi** [comment]
@olivecha Sure!

There were some alterations to address the issues that were made in multiple commits. I will insert the comment in each of them.

**Comment by thiago-glissoi** [comment]
> Could you mention the issue number (#2) in the commit messages of the changes addressing the issue ? (Same for all issues, so we can track what was done to remediate the issues)

Done!

**Comment by olivecha** [comment]
This is much better, the documentation of the sub-functions is a bit hard to get to, but I guess this is a Matlab thing.

You could mention when (important) sub-functions are called in the three steps of the main function instead of naming then alphabetically, as this would make it easier to understand their utility, but this would not be necessary for publication.
