### ISSUE TITLE
Dependencies and MATLAB

### ISSUE THREAD

**Issue by olivecha** [thiago-glissoi/FFF-Line-Segmentation#3]
Please mention the required MATLAB toolboxes to run the code (Signal Processing) in the installation instructions.

Also, the fact that MATLAB is a licensed coding language is not really aligned with open sources principles. It would not be reasonable to request that the project to be written in another language (python would work well here). However, could you check if all the MATLAB function used are available in octave and if so mention it in the installation section ?

**Comment by thiago-glissoi** [comment]
Hey @olivecha  

Thanks for heads up and for contributing!

We've added support for Octave. Also, the information about dependencies (MATLAB Toolboxes | Octave Packages) has been included in the README.

If you have any more ideas or questions, don't hesitate to let us know.

Best,

Thiago
