### ISSUE TITLE
User and `fff_segmenter` inputs

### ISSUE THREAD

**Issue by olivecha** [thiago-glissoi/FFF-Line-Segmentation#5]
There is an inconsistency on how the input to `fff_segmenter` is processed versus the user input. The function call signature is API-like, requires MATLAB arrays to be defined beforehand and needs to be called from a MATLAB script or console, but it also requires user input. 

I would suggest either: 
- removing the arguments from the function call and adding a prompt that asks for the path of the data, which is then loaded from inside the function.
- Creating a second script meant to be edited by the user, where the data is loaded, and the function is called as-is.

**Comment by thiago-glissoi** [comment]
@olivecha 👋

Thanks for the issue.

We've made significant changes to how users input the necessary data, signal names, and segmentation options. Upon execution, the `fff_segmenter` script now displays graphical interfaces for user input, available for both MATLAB and Octave.

Please check if these changes meet the requirements.

Best,

Thiago

**Comment by olivecha** [comment]
This is nice, but would require a little more documentation, as it was really not clear what the fields are for a new user. 
1. What format is expected in the "Select Data" file loader
2. That the sampling frequency is required. This is a bit uncommon, as most (if not all) audio formats store the sampling frequency in the metadata.
3. That the "Identification" fields are names of the associated variables in the .mat file. It would really help to have the variables names in the file in a drop-down menu.
4. Add a more detailed description of what the segmentation mode and unit choice do in the "How to use" section
5. If you run the App with the default "No" values, there is no output?

Adding annotations with arrows in the graphical interface figure could do the trick

**Comment by thiago-glissoi** [comment]
@olivecha  👋

> 1. What format is expected in the "Select Data" file loader

The information was inserted through an annotation on the graphical interface figure and to the `README.md` document.

> 2. That the sampling frequency is required. This is a bit uncommon, as most (if not all) audio formats store the sampling frequency in the metadata.

The information was inserted in the `README.md` document.

> 3. That the "Identification" fields are names of the associated variables in the .mat file. It would really help to have the variables names in the file in a drop-down menu.

The information was inserted through an annotation on the graphical interface figure and to the `README.md` document.

> 4. Add a more detailed description of what the segmentation mode and unit choice do in the "How to use" section

The information was inserted in the `README.md` document.

> 5. If you run the App with the default "No" values, there is no output?

If you run the `fff_segmenter` script with default values, that is with "No" values, there still will be the segmentation results output to the current MATLAB/Octave workspace.  The information was inserted in the `README.md` document.

> Adding annotations with arrows in the graphical interface figure could do the trick

Annotations had been inserted in the graphical interface figure.


If additional informations are required, please let me know.

Best,
Thiago

**Comment by olivecha** [comment]
Closing as this is acceptable
