### ISSUE TITLE
Add contributing guidelines to README

### ISSUE THREAD

**Issue by olivecha** [thiago-glissoi/FFF-Line-Segmentation#7]
Add communities guidelines to the README:

Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

**Comment by thiago-glissoi** [comment]
Hey @olivecha  

Thanks for bringing this up and for contributing!

We've added the community guidelines to the repository. You can check them out in the README file.

If you have any more suggestions or questions, feel free to reach out.

Cheers,

Thiago

**Comment by olivecha** [comment]
Lgtm, you used code style highlights in the first point which I am not sure if you meant to do? Perhaps bold or italic would be better suited. (This is not important for the acceptance of the paper so I'm closing the issue)
