### ISSUE TITLE
Overall code quality

### ISSUE THREAD

**Issue by olivecha** [thiago-glissoi/FFF-Line-Segmentation#8]
This would not be required for the acceptance of the paper, but `checkcode("fff_segmenter.m")` outputs the following suggestions:

- L 631 (C 20-27): To improve performance, use 'isscalar' instead of length comparison.
`631    if aux == 1`
- L 1154 (C 4-9): Consider using ISA instead of comparing the class name.
`1154    if strcmp(class(res),'double')`

Also some loops could be removed using indexes, like replacing:
```matlab
for i = 1:length(dirX)
    if dirX(i) > 2
        dirXAdjusted(i) = 5;
    else
        dirXAdjusted(i) = 0;
    end
end

for i = 1:length(dirY)
    if dirY(i) > 2
        dirYAdjusted(i) = 5;
    else
        dirYAdjusted(i) = 0;
    end
end
```
with:
```matlab
dirXAdjusted(dirX > 2) = 5;
dirXAdjusted(dirX < 2) = 0;
dirYAdjusted(dirY < 2) = 0;
dirYAdjusted(dirY > 2) = 5;
```

**Comment by thiago-glissoi** [comment]
Hey @olivecha 

The authors appreciate the issue.

We have made the required alterations to the `fff_segmenter` code.

Please, if additional alterations are necessary, let us know.

Att,

Thiago

**Comment by olivecha** [comment]
Closing this as this was not necessary for publication and was addressed by the authors.
